[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "npm install -g pnpm && pnpm install && pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
